[tool.poetry]
name = "pdf-processing-app"
version = "0.1.0"
description = "A project to process PDFs and interact with the Gemini API and Airtable"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.1"
google-generativeai = "^0.6.0"
requests = "^2.26.0"
PyMuPDF = "^1.20.0"
tqdm = "^4.62.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
