[tool.poetry]
name = "your_project_name"
version = "0.1.0"
description = ""
authors = ["your_name <your_email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.1"
google-generativeai = "^1.0.0"
flask = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
